-- V28: 为新表补充 BaseEntity 公用列（created_at/updated_at/deleted）
-- 部分早期 migration 未包含这些列

-- V23 tables
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

ALTER TABLE sys_permission ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_permission ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_permission ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

ALTER TABLE sys_role_permission ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_role_permission ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_role_permission ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

ALTER TABLE sys_user_role ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_user_role ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_user_role ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

-- V24 tables
ALTER TABLE approval_add_sign ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE approval_add_sign ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE approval_add_sign ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

ALTER TABLE approval_timeout_record ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE approval_timeout_record ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE approval_timeout_record ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

-- V25 tables (sys_dict_type/sys_dict_item already have created_at/updated_at)
ALTER TABLE sys_dict_type ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
ALTER TABLE sys_dict_item ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

-- V26 tables
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_notification ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

ALTER TABLE sys_notification_template ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_notification_template ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;

-- V27 table
ALTER TABLE sys_file ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sys_file ADD COLUMN IF NOT EXISTS deleted INTEGER DEFAULT 0;
