package com.sasac.platform.supervision.alert.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.sasac.platform.common.base.BaseEntity;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Alert record entity representing a triggered alert.
 * <p>
 * Maps to the {@code alert_record} table. Alerts are generated by scheduled
 * scans or manual operations and follow a lifecycle from ACTIVE to
 * ACKNOWLEDGED to RESOLVED.
 */
@Getter
@Setter
@TableName("alert_record")
public class AlertRecord extends BaseEntity {

    /**
     * The rule that triggered this alert.
     */
    private Long ruleId;

    /**
     * Alert type: MAINTENANCE_EXPIRY, INSPECTION_OVERDUE, BORROW_OVERDUE, IDLE_ASSET.
     */
    private String alertType;

    /**
     * Short alert title.
     */
    private String title;

    /**
     * Detailed alert description.
     */
    private String content;

    /**
     * JSON data payload with additional context.
     */
    private String alertData;

    /**
     * Status: ACTIVE, ACKNOWLEDGED, RESOLVED.
     */
    private String status = "ACTIVE";

    /**
     * User ID who handled the alert.
     */
    private Long handledBy;

    /**
     * Timestamp when the alert was handled.
     */
    private LocalDateTime handledAt;

    /**
     * Tenant ID for multi-tenancy.
     */
    private Long tenantId;

    /**
     * Reference business record ID (e.g. inspection task ID, asset ID).
     */
    private Long refId;
}
